import subprocess
import os
import shutil


def bexec(dir, bashCommand=None):
    process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE, cwd=dir)
    output, error = process.communicate()
    out = output.decode()
    return out


# generated by traversal below : )
repos = [
    "src/fun_repo"
]

for root, subdirs, files in os.walk("src"):
    out = os.listdir(root)
    if ".git" not in out:  # or ".gitlab-ci.yml" in out:
        continue

    if root not in repos:
        continue

    out = bexec(root, "git remote -v")
    if "gitlab" not in out:
        continue

    shutil.copy2(".gitlab-ci.yml", root)
    # bexec(root, "git checkout -b CI")
    bexec(root, "git add .gitlab-ci.yml")
    bexec(root, "git commit -m CI")
    out = bexec(root, "git push -u origin CI")
    print(out)
    # print(bexec(root, "git status"))
